// Monte Carlo job report (/report?job=<id>, also /fleet?job=<id>).
// The HTML report of a finished simulation (records + TDA regimes + ML scores
// from CortXplorer, with what-if re-runs) plus its PDF and Excel, generated by
// POST /v1/reports/job. Two kinds of job share the page:
//   fleet     the fleet report (render)
//   scenario  any other table: tiles, charts and tables are built from what
//             the job describes (renderScenario) — no dataset-specific code
// Both end with the TDA Mapper graph the job was sent (mapper_view.js).
// Every number comes from the service; missing values render as "–".

const POLL_MS = 700;
const ACTIVE = ["queued", "running"];
const $ = (id) => document.getElementById(id);
const cssVar = (n) => getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const pct = (v, d = 1) => (v == null ? "–" : `${(v * 100).toFixed(d)}%`);
const num = (v, d = 0) => (v == null ? "–" : Number(v).toLocaleString("en-GB", { minimumFractionDigits: d, maximumFractionDigits: d }));
const eur = (v) => (v == null ? "–" : `€${num(v)}`);
// Plotly needs plain colours: "#rrggbb" + alpha → "rgba(...)"
const rgba = (hex, a) => {
  const h = hex.replace("#", "");
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
  return `rgba(${r},${g},${b},${a})`;
};

// adaptive number and "value in the format the job asked for" (scenario jobs)
const auto = (v) => {
  if (v == null || !Number.isFinite(v)) return "–";
  const a = Math.abs(v);
  return num(v, a >= 1000 ? 0 : a >= 100 ? 1 : a >= 1 ? 2 : 3);
};
function fmtVal(v, fmt, unit) {
  if (v == null) return "–";
  const s = fmt === "pct" ? pct(v) : fmt === "int" ? num(v) : auto(v);
  if (!unit || fmt === "pct") return s;
  return unit === "€" || unit === "$" || unit === "£" ? `${unit}${s}` : `${s} ${unit}`;
}
const PLOT_CONFIG = { displaylogo: false, responsive: true, scrollZoom: true };

const state = { jobId: null, timer: null, generation: 0, kind: "fleet", unit: "operating days", graph: null, tdaView: "mapper" };

// Which report this is: toggles the what-if fields and the headings.
function setKind(kind, sc) {
  state.kind = kind;
  const scenario = kind === "scenario";
  document.querySelectorAll(".fleet-only").forEach((e) => { e.hidden = scenario; });
  document.querySelectorAll(".scenario-only").forEach((e) => { e.hidden = !scenario; });
  $("fleet-charts").hidden = scenario;
  $("gx-charts").hidden = !scenario;
  const title = scenario ? (sc.config.title || "Scenario simulation") : "Fleet management";
  state.unit = scenario ? sc.summary.dashboard.unit : "operating days";
  $("rp-eyebrow").textContent = `${title} · Monte Carlo on TDA / ML results`;
  $("rp-title").textContent = scenario ? "Monte Carlo Simulation with TDA" : "Monte Carlo Simulation in Fleet Management";
  $("rp-lede").textContent = scenario
    ? `From “what might happen?” to “how likely is it?”: thousands of possible ${state.unit}, sampled from the real ${sc.config.record_label} and the regimes TDA found in them.`
    : "From “what might happen?” to “how likely is it?”: thousands of possible operating days, sampled from real fleet records and the regimes TDA found in them.";
  $("lbl-clean").textContent = scenario
    ? "Exclude records the ML model flags as anomalies (score ≥ 0.6)"
    : "Exclude operating records the ML model flags as anomalies (score ≥ 0.6)";
}

// ── API (JSON in, JSON envelope out) ────────────────────────────────────────
async function api(path, options = {}) {
  const res = await fetch(path, { headers: { "Content-Type": "application/json", Accept: "application/json" }, ...options });
  let body = null;
  try { body = await res.json(); } catch { /* not JSON */ }
  if (!res.ok || !body || body.status === "error") throw new Error((body && body.message) || `${res.status} ${res.statusText}`);
  return body.data;
}

function showError(msg) {
  $("error").textContent = msg || "";
  $("error").hidden = !msg;
}

function node(tag, cls, text, parent) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text !== undefined) e.textContent = text;
  if (parent) parent.appendChild(e);
  return e;
}

// ── charts ─────────────────────────────────────────────────────────────────
function baseLayout(xTitle, yTitle, extra = {}) {
  const muted = cssVar("--muted"), line = cssVar("--line");
  return {
    paper_bgcolor: "rgba(0,0,0,0)", plot_bgcolor: "rgba(0,0,0,0)",
    font: { color: muted, size: 11 }, margin: { l: 52, r: 16, t: 28, b: 44 }, bargap: 0.06, showlegend: false,
    xaxis: { title: { text: xTitle }, gridcolor: line, zeroline: false },
    yaxis: { title: { text: yTitle }, gridcolor: line, zeroline: false },
    ...extra,
  };
}

function vline(x, color, label, dash = "dash", row = 0) {
  return {
    shape: { type: "line", x0: x, x1: x, yref: "paper", y0: 0, y1: 1, line: { color, width: 2, dash } },
    note: { x, yref: "paper", y: 1.03 - row * 0.09, text: label, showarrow: false, font: { color, size: 11 }, xanchor: "left", xshift: 4 },
  };
}

function histChart(id, h, color, xTitle, lines) {
  if (!h || !h.counts.length) { Plotly.purge(id); return; }
  const total = h.counts.reduce((a, b) => a + b, 0) || 1;
  const mids = h.counts.map((_, i) => (h.edges[i] + h.edges[i + 1]) / 2);
  const width = h.edges.length > 1 ? (h.edges[1] - h.edges[0]) * 0.92 : 1;
  Plotly.react(id, [{ type: "bar", x: mids, y: h.counts.map((c) => c / total), width, marker: { color },
      hovertemplate: "%{x:,.0f}: %{y:.1%}<extra></extra>" }],
    baseLayout(xTitle, "probability", { shapes: lines.map((l) => l.shape), annotations: lines.map((l) => l.note) }),
    { displaylogo: false, responsive: true, scrollZoom: true });
}

// ── render ─────────────────────────────────────────────────────────────────
function tile(parent, k, v) {
  const t = node("div", "tile", undefined, parent);
  node("div", "k", k, t);
  node("div", "v", v, t);
}

function output(parent, kind, strong, text) {
  const o = node("div", "out", undefined, parent);
  node("span", `ico ${kind}`, kind === "good" ? "✓" : kind === "bad" ? "!" : "•", o);
  const body = node("div", "", undefined, o);
  node("b", "", strong, body);
  body.appendChild(document.createTextNode(` ${text}`));
}

function fillForm(cfg, nSims) {
  $("in-fleet").value = cfg.fleet_size;
  $("in-target").value = cfg.delivery_target_h;
  $("in-sla").value = Math.round(cfg.sla_on_time * 100);
  $("in-sims").value = nSims;
  $("in-clean").checked = cfg.exclude_anomalies_above != null;
}

// ── scenario report (any dataset) ───────────────────────────────────────────
function renderContext(c, has) {
  const tda = $("tda"); tda.replaceChildren();
  if (!has) { node("p", "note", "The sender did not include TDA / ML context.", tda); return; }
  node("p", "note", `Structures: ${num(c.n_clusters)} clusters (regimes), ${num(c.n_noise)} noise records · β₁ = ${c.structure ? num(c.structure.betti_1) : "–"} loops`, tda);
  node("p", "note", `ML anomaly model: ${num(c.n_anomalies_high)} records score HIGH (≥ 0.60)`, tda);
  [["Relationships", c.relationships], ["Patterns between regimes", c.patterns]].forEach(([title, items]) => {
    if (!items || !items.length) return;
    node("div", "label", title, tda);
    const ul = node("ul", "plain", undefined, tda);
    items.forEach((x) => node("li", "", x, ul));
  });
  if (c.source) node("p", "note", `Source: ${c.source}`, tda);
}

function renderConvergence(cv, label, tickformat, note) {
  const warm = cssVar("--warm");
  if (!cv.n.length) { Plotly.purge("c-conv"); $("conv-note").textContent = ""; return; }
  Plotly.react("c-conv", [
    { x: cv.n.concat([...cv.n].reverse()), y: cv.hi.concat([...cv.lo].reverse()), fill: "toself", type: "scatter",
      line: { width: 0 }, fillcolor: rgba(warm, 0.2), hoverinfo: "skip" },
    { x: cv.n, y: cv.p, type: "scatter", line: { color: warm, width: 2 }, hovertemplate: `%{x:,} scenarios: %{y:${tickformat || ",.3f"}}<extra></extra>` }],
    baseLayout("scenarios (log scale)", label, { xaxis: { type: "log", gridcolor: cssVar("--line"), title: { text: "scenarios (log scale)" } },
      yaxis: { tickformat: tickformat || "", gridcolor: cssVar("--line"), title: { text: label } } }), PLOT_CONFIG);
  $("conv-note").textContent = note;
}

function renderScenario(sc) {
  const s = sc.summary, k = s.kpi, cfg = sc.config, dash = s.dashboard;
  const period = cfg.period_label, unit = dash.unit, records = cfg.record_label;
  const tones = { blue: cssVar("--series-1"), good: cssVar("--series-3"), warm: cssVar("--warm"), bad: cssVar("--bad") };
  setKind("scenario", sc);
  $("result").hidden = false;
  $("in-period").value = cfg.period_size;
  $("lbl-period").textContent = `${records[0].toUpperCase()}${records.slice(1)} per ${period}`;
  $("in-sims").value = sc.n_completed;
  $("in-clean").checked = cfg.exclude_anomalies_above != null;

  const ins = $("inputs"); ins.replaceChildren();
  $("inputs-sub").textContent = "observed in the data, per record (P5 – P95)";
  tile(ins, `${records[0].toUpperCase()}${records.slice(1)} in data`, cfg.n_periods ? `${num(cfg.n_records)} · ${num(cfg.n_periods)} ${unit}` : num(cfg.n_records));
  s.metrics.forEach((m) => {
    const q = s.inputs.metrics[m.key];
    tile(ins, m.label + (m.unit ? ` (${m.unit})` : ""), q ? `${fmtVal(q.p5, m.record_fmt)} – ${fmtVal(q.p95, m.record_fmt)}` : "–");
  });

  const eng = $("engine"); eng.replaceChildren();
  node("div", "eyebrow", "Monte Carlo engine", eng);
  node("div", "big", num(sc.n_completed), eng);
  node("div", "", `simulated ${unit}`, eng);
  node("div", "note", `${num(cfg.n_pool)} of ${num(cfg.n_records)} records · ${num(cfg.period_size)} ${records} per ${period}`, eng);
  node("div", "note", cfg.n_periods
    ? `Each scenario draws a real ${period} and resamples its ${records}`
    : `Each scenario resamples ${num(cfg.period_size)} ${records} from the whole dataset`, eng);

  const out = $("outputs"); out.replaceChildren();
  s.metrics.forEach((m) => {
    const how = m.agg === "sum" ? "total" : "average";
    let text = `expected ${m.label} (${how} per ${period}); 90% of ${unit}: ${fmtVal(k[`${m.key}_p5`], m.fmt, m.unit)} – ${fmtVal(k[`${m.key}_p95`], m.fmt, m.unit)}`;
    if (m.alert != null) text += ` · P(> ${fmtVal(m.alert, m.fmt, m.unit)}) = ${pct(k[`${m.key}_p_over`])}`;
    output(out, "info", fmtVal(k[`${m.key}_mean`], m.fmt, m.unit), text);
  });
  if (s.anomalies.high_risk) {
    output(out, k.p_any_high > 0.5 ? "bad" : "info", pct(k.p_any_high), `probability a ${period} contains at least one high-risk record (anomaly score ≥ ${cfg.high_anomaly})`);
    output(out, "info", auto(k.high_mean), `high-risk ${records} expected per ${period} (P95 ${num(k.high_p95)} of ${num(cfg.period_size)})`);
  }

  const kp = $("kpis"); kp.replaceChildren();
  dash.tiles.slice(0, 4).forEach((t) => {
    const e = node("div", "card kpi", undefined, kp);
    node("div", "k", t.label, e);
    node("div", "v", fmtVal(k[t.key], t.fmt, t.unit), e).style.color = tones[t.tone] || cssVar("--accent");
    node("div", "s", (t.sub || []).map((p) => (p.text != null ? p.text : fmtVal(p.key ? k[p.key] : p.value, p.fmt, t.unit))).join(""), e);
  });

  const charts = $("gx-charts"); charts.replaceChildren();
  dash.charts.forEach((c) => {
    const card = node("div", "card", undefined, charts);
    node("h3", "", c.title, card);
    node("div", "chart", undefined, card).id = `gx-${c.key}`;
  });
  dash.charts.forEach((c) => {
    const lines = [];
    c.lines.forEach((l) => {
      const v = l.key ? k[l.key] : l.value;
      if (v != null) lines.push(vline(v, tones[l.tone], `${l.label} ${fmtVal(v, l.fmt, c.unit)}`, "dash", lines.length));
    });
    histChart(`gx-${c.key}`, s.hist[c.key], tones[c.tone] || tones.blue, c.x_title, lines);
  });

  const tb = $("regimes"); tb.replaceChildren();
  const tails = s.tails || [];
  $("regimes-note").textContent = "Each regime is a cluster TDA found in the records. The simulation samples from all of them; the table shows how each behaves in the data"
    + (tails.length ? `, and how over-represented it is in the ${unit} where a metric is in its top 5% (×1 = as often as usual).` : ".");
  const head = tb.createTHead().insertRow();
  ["Regime (TDA cluster)", "Records", "Share", "Avg anomaly", "High-risk share", ...s.metrics.map((m) => m.label),
   ...tails.map((t) => `In high-${t.label} ${unit}`)].forEach((h) => node("th", "", h, head));
  const body = tb.createTBody();
  [...sc.results].sort((a, b) => (b.high_risk_share || 0) - (a.high_risk_share || 0)).forEach((g) => {
    const tr = body.insertRow();
    [g.label, num(g.records), pct(g.share), auto(g.anomaly_mean), pct(g.high_risk_share),
     ...s.metrics.map((m) => fmtVal(g.metrics[m.key], m.record_fmt)),
     ...tails.map((t) => (g.tail_lift[t.key] == null ? "–" : `×${g.tail_lift[t.key].toFixed(2)}`))]
      .forEach((v) => { tr.insertCell().textContent = v; });
  });

  renderContext(s.context || {}, !!s.context);
  const a = s.anomalies, an = $("anoms"); an.replaceChildren();
  node("p", "", `${num(a.high_risk)} of ${num(cfg.n_records)} records score HIGH (≥ ${cfg.high_anomaly}).`, an);
  if (a.threshold == null) {
    node("p", "note", "All records were used (anomaly exclusion off). Switch it on above to leave out the records the ML model flags; check first that they are data errors and not real events.", an);
  } else {
    node("p", "note", `${num(a.excluded)} records with an ML anomaly score ≥ ${a.threshold} were left out of the sampling pool.`, an);
    if (a.record_ids.length) node("p", "note", a.record_ids.slice(0, 30).join(" · ") + (a.excluded > 30 ? " …" : ""), an);
  }

  const cv = s.convergence, last = cv.p.length - 1, m0 = s.metrics[0];
  renderConvergence(cv, cv.label || "estimate", m0.fmt === "pct" ? ".1%" : "", last >= 0
    ? `After ${num(sc.n_completed)} scenarios: ${cv.label} = ${fmtVal(cv.p[last], m0.fmt, m0.unit)}, 95% CI ${fmtVal(cv.lo[last], m0.fmt, m0.unit)} – ${fmtVal(cv.hi[last], m0.fmt, m0.unit)}.${sc.stopped_early ? " Stopped early by the time budget." : ""}`
    : "");
}

// ── relationship significance (when the job carried the test) ───────────────
function renderRelationships(rel, error) {
  const card = $("rel-card"), tb = $("rel-table"), badge = $("rel-verdict");
  card.hidden = !rel && !error;
  tb.replaceChildren();
  badge.textContent = "";
  badge.className = "verdict";
  if (error) { $("rel-note").textContent = `The relationship test failed: ${error}`; return; }
  if (!rel) return;
  const s = rel.summary, cfg = rel.config;
  if (!rel.results.length) { $("rel-note").textContent = s.note || "No relationship could be tested."; return; }
  badge.textContent = `${num(s.n_significant)} of ${num(s.n_pairs)} significant`;
  badge.classList.add(s.n_significant ? "holds" : "partly");
  $("rel-note").textContent = `CortXplorer links a ${s.label_a} label with a ${s.label_b} label when their records concentrate in the same Mapper groups (lift > 1). `
    + `Here each lift is compared with ${num(rel.n_completed)} runs in which the labels were re-assigned at random (${cfg.null}): `
    + `p = how often chance gives a lift this extreme, q = the same after correcting for testing ${num(s.n_pairs)} pairs. Significant at q ≤ ${cfg.alpha}. `
    + "With many records even a small lift becomes significant, so read the lift as the size of the effect.";
  const head = tb.createTHead().insertRow();
  [s.label_a, s.label_b, "Lift", "By chance (95% range)", "Records with both", "p", "q", "Verdict"].forEach((h) => node("th", "", h, head));
  const body = tb.createTBody();
  rel.results.forEach((r) => {
    const tr = body.insertRow();
    [r.a, r.b, `×${r.lift.toFixed(2)}`, `×${r.null_lo.toFixed(2)} – ×${r.null_hi.toFixed(2)}`, num(r.n_cooccur),
     r.p_value < 0.001 ? "< 0.001" : r.p_value.toFixed(3), r.q_value < 0.001 ? "< 0.001" : r.q_value.toFixed(3)]
      .forEach((v) => { tr.insertCell().textContent = v; });
    const cell = tr.insertCell();
    cell.textContent = r.verdict;
    cell.className = !r.significant ? "none" : r.direction === "above" ? "holds" : "fails";
  });
  if (tb.rows[0]) tb.rows[0].cells[1].style.textAlign = "left";
  [...body.rows].forEach((row) => { row.cells[1].style.textAlign = "left"; });
}

// ── backtest (both kinds): simulated from the first periods, checked on the last ─
const VERDICT_CLASS = { holds: "holds", "partly holds": "partly", "does not hold": "fails" };

function renderBacktest(bt) {
  const card = $("backtest-card");
  card.hidden = !bt;                                         // jobs from before the backtest existed
  if (!bt) return;
  const tb = $("backtest"), badge = $("backtest-verdict");
  tb.replaceChildren();
  if (!bt.available) {
    badge.textContent = "";
    badge.className = "verdict";
    $("backtest-note").textContent = `Not available: ${bt.reason}.`;
    return;
  }
  badge.textContent = bt.verdict;
  badge.className = `verdict ${VERDICT_CLASS[bt.verdict] || ""}`;
  $("backtest-note").textContent = `The simulation was fed only the first ${num(bt.train_periods)} ${bt.unit} (up to ${bt.train_until}); `
    + `the last ${num(bt.test_periods)} (${bt.test_from} – ${bt.test_until}) were held back and compared with its ${bt.band[0]}–${bt.band[1]}% range. `
    + `If the past describes the future, about ${pct(bt.expected_coverage, 0)} of the held-back ${bt.unit} fall inside the range; `
    + `here ${pct(bt.coverage, 0)} do on average. ≥ 80% = holds, 60–80% = partly holds, below = does not hold.`;
  const head = tb.createTHead().insertRow();
  ["Metric", `Simulated range (${bt.band[0]}–${bt.band[1]}%)`, "Simulated mean", "Observed in held-back (mean)", "Observed min – max",
   "Inside the range", "Verdict"].forEach((h) => node("th", "", h, head));
  const body = tb.createTBody();
  bt.metrics.forEach((r) => {
    const tr = body.insertRow(), f = (v) => fmtVal(v, r.fmt, r.unit);
    [r.label, `${f(r.sim_lo)} – ${f(r.sim_hi)}`, f(r.sim_mean), f(r.observed_mean), `${f(r.observed_min)} – ${f(r.observed_max)}`,
     pct(r.coverage, 0)].forEach((v) => { tr.insertCell().textContent = v; });
    const cell = tr.insertCell();
    cell.textContent = r.verdict;
    cell.className = VERDICT_CLASS[r.verdict] || "";
  });
}

// ── TDA Mapper (both kinds): the graph the job was sent ─────────────────────
async function renderMapper(jobId, generation) {
  $("mapper-card").hidden = true;
  state.graph = null;
  let g = null;
  try {
    g = (await api("/v1/reports/job", { method: "POST", body: JSON.stringify({ job_id: jobId, format: "json" }) })).graph;
  } catch { /* the Mapper section is optional */ }
  if (generation !== state.generation || !g || !g.nodes || !g.nodes.length) return;
  state.graph = g;
  $("mapper-card").hidden = false;
  drawMapper();
}

// Mapper ↔ Galaxy: the same graph with another look (state.tdaView).
function drawMapper() {
  const g = state.graph;
  if (!g) return;
  const gv = MapperView.graphView(g), shown = MapperView.labelled(g, gv), view = MapperView.VIEWS[state.tdaView];
  document.querySelectorAll(".seg button[data-tda]").forEach((b) => b.setAttribute("aria-pressed", String(b.dataset.tda === state.tdaView)));
  $("mapper-title").textContent = state.tdaView === "galaxy" ? gv.title.replace("TDA Mapper", "TDA Galaxy") : gv.title;
  $("mapper-hint").textContent = MapperView.hint(g, gv, state.tdaView);
  MapperView.keyTable($("mapper-table"), shown, gv, $("mapper-note"));
  Plotly.purge("mapper-plot");
  Plotly.react("mapper-plot", view.traces(g, gv, shown, null), view.layout(g, gv, view.eye), PLOT_CONFIG);
}

function render(f) {
  setKind("fleet");
  $("inputs-sub").textContent = "observed in the data";
  $("regimes-note").textContent = "Each regime is a cluster TDA found in the fleet records. The simulation samples from all of them; the table shows how each behaves in the data.";
  const k = f.summary.kpi, cfg = f.config, inp = f.summary.inputs || {};
  const good = cssVar("--good"), bad = cssVar("--bad"), accent = cssVar("--accent"), warm = cssVar("--warm");
  const s1 = cssVar("--series-1"), s3 = cssVar("--series-3"), dim = cssVar("--dim");
  $("result").hidden = false;
  fillForm(cfg, f.n_completed);

  const ins = $("inputs"); ins.replaceChildren();
  const r = (q, fmt) => (q ? `${fmt(q.p5)} – ${fmt(q.p95)}` : "–");
  tile(ins, "Vehicles in data", `${num(inp.vehicles)} · ${num(inp.days)} days`);
  tile(ins, "Daily demand (P5–P95)", r(inp.daily_demand, num));
  tile(ins, "Driver availability", r(inp.driver_availability, (v) => pct(v, 0)));
  tile(ins, "Breakdowns per day", r(inp.daily_breakdowns, num));
  tile(ins, "Fuel consumption", `${r(inp.fuel_l_per_100km, (v) => num(v, 1))} L/100 km`);
  tile(ins, "Route duration", `${r(inp.route_duration_h, (v) => num(v, 1))} h`);
  tile(ins, "Fuel price", `${r(inp.fuel_price_eur_l, (v) => num(v, 2))} €/L`);
  tile(ins, "Maintenance per breakdown", r(inp.maintenance_cost_per_breakdown, eur));

  const eng = $("engine"); eng.replaceChildren();
  node("div", "eyebrow", "Monte Carlo engine", eng);
  node("div", "big", num(f.n_completed), eng);
  node("div", "", "simulated operating days", eng);
  node("div", "note", `${num(cfg.n_pool)} of ${num(cfg.n_records)} records · ${cfg.n_days} historical days · fleet of ${num(cfg.fleet_size)}`, eng);
  node("div", "note", "Each scenario draws a real day and resamples its vehicle records", eng);

  const out = $("outputs"); out.replaceChildren();
  output(out, k.p_meet_sla >= 0.9 ? "good" : "bad", pct(k.p_meet_sla), `probability a day meets the on-time SLA (≥ ${pct(cfg.sla_on_time, 0)} of deliveries on time)`);
  output(out, k.p_miss_sla > 0.1 ? "bad" : "good", pct(k.p_miss_sla), "probability of missing the delivery target");
  output(out, "info", `${num(k.vehicles_required_mean)} vehicles`, `expected to meet demand (95th percentile: ${num(k.vehicles_required_p95)}; fleet: ${num(k.fleet_size)})`);
  output(out, "info", `${num(k.fuel_l_mean)} L`, `expected daily fuel consumption (P95 ${num(k.fuel_l_p95)} L)`);
  output(out, "info", pct(k.p_breakdowns_over_alert), `probability of more than ${k.breakdown_alert} vehicle breakdowns in a day`);
  output(out, "info", eur(k.maint_cost_mean), `expected maintenance cost per day (P95 ${eur(k.maint_cost_p95)})`);

  const kp = $("kpis"); kp.replaceChildren();
  [["Fleet availability", pct(k.fleet_availability_mean), "vehicles with driver and no breakdown", good],
   [`Delivered within ${cfg.delivery_target_h} h`, pct(k.p_delivery_within_target), "of all planned deliveries (missed ones count as late)", accent],
   ["Expected daily fuel cost", eur(k.fuel_cost_mean), `P95 ${eur(k.fuel_cost_p95)}`, warm],
   ["Breakdown risk", pct(k.p_breakdowns_over_alert), `P(> ${k.breakdown_alert} breakdowns per day)`, bad]]
    .forEach(([label, v, sub, color]) => {
      const e = node("div", "card kpi", undefined, kp);
      node("div", "k", label, e);
      node("div", "v", v, e).style.color = color;
      node("div", "s", sub, e);
    });

  const dt = f.summary.delivery_time;
  if (dt.share.length) {
    const mids = dt.share.map((_, i) => (dt.edges[i] + dt.edges[i + 1]) / 2);
    const tgt = vline(cfg.delivery_target_h, bad, `target ${cfg.delivery_target_h} h`);
    Plotly.react("c-delivery", [{ type: "bar", x: mids, y: dt.share, width: (dt.edges[1] - dt.edges[0]) * 0.92,
        marker: { color: mids.map((m) => (m <= cfg.delivery_target_h ? s1 : dim)) },
        hovertemplate: "%{x:.2f} h: %{y:.1%}<extra></extra>" }],
      baseLayout("delivery time (hours)", "probability", {
        shapes: [tgt.shape],
        annotations: [tgt.note, { xref: "paper", yref: "paper", x: 1, y: 0.92, xanchor: "right", showarrow: false,
          text: `P(within ${cfg.delivery_target_h} h | delivered) = ${pct(dt.p_within_target)}`, font: { color: cssVar("--ink"), size: 12 } }],
      }), { displaylogo: false, responsive: true, scrollZoom: true });
  }
  const H = f.summary.hist;
  histChart("c-vehicles", H.vehicles_required, s1, "number of vehicles", [
    vline(k.vehicles_required_mean, warm, `expected ${num(k.vehicles_required_mean)}`, "dash", 0),
    vline(k.vehicles_required_p95, bad, `P95 ${num(k.vehicles_required_p95)}`, "dash", 1),
    vline(k.fleet_size, good, `fleet ${num(k.fleet_size)}`, "dot", 2),
  ]);
  histChart("c-maint", H.maint_cost, s3, "daily maintenance cost (€)", [
    vline(k.maint_cost_mean, warm, `expected ${eur(k.maint_cost_mean)}`, "dash", 0),
    vline(k.maint_cost_p95, bad, `P95 ${eur(k.maint_cost_p95)}`, "dash", 1),
  ]);
  const o = f.summary.outcome;
  Plotly.react("c-outcome", [{ type: "pie", hole: 0.55, sort: false, labels: ["On time", "Delayed"],
      values: [o.on_time, o.delayed], marker: { colors: [good, bad] }, textinfo: "percent",
      textfont: { color: "#fff", size: 13 }, hovertemplate: "%{label}: %{percent}<extra></extra>" }],
    { ...baseLayout("", ""), showlegend: true, legend: { orientation: "h", y: -0.05 }, margin: { l: 10, r: 10, t: 10, b: 30 } },
    { displaylogo: false, responsive: true, scrollZoom: true });

  const tb = $("regimes"); tb.replaceChildren();
  const head = tb.createTHead().insertRow();
  ["Regime (TDA cluster)", "Records", "Share", "On time", `Within ${cfg.delivery_target_h} h`, "Breakdown rate",
   "Availability", "Fuel L / record", "Maintenance € / record", "Share of late deliveries"]
    .forEach((h) => node("th", "", h, head));
  const body = tb.createTBody();
  [...f.results].sort((a, b) => b.late_deliveries_share - a.late_deliveries_share).forEach((g) => {
    const tr = body.insertRow();
    [g.label, num(g.records), pct(g.share), pct(g.on_time_share), pct(g.within_target_share), pct(g.breakdown_rate),
     pct(g.availability), num(g.fuel_l_mean, 1), eur(g.maint_cost_mean), pct(g.late_deliveries_share)]
      .forEach((v) => { tr.insertCell().textContent = v; });
  });

  const c = f.summary.context || {}, tda = $("tda"); tda.replaceChildren();
  if (!f.summary.context) node("p", "note", "The sender did not include TDA / ML context.", tda);
  else {
    node("p", "note", `Structures: ${num(c.n_clusters)} clusters (regimes), ${num(c.n_noise)} noise records · β₁ = ${c.structure ? num(c.structure.betti_1) : "–"} loops`, tda);
    node("p", "note", `ML anomaly model: ${num(c.n_anomalies_high)} records score HIGH (≥ 0.60)`, tda);
    [["Relationships", c.relationships], ["Patterns between regimes", c.patterns]].forEach(([title, items]) => {
      if (!items || !items.length) return;
      node("div", "label", title, tda);
      const ul = node("ul", "plain", undefined, tda);
      items.forEach((x) => node("li", "", x, ul));
    });
    if (c.source) node("p", "note", `Source: ${c.source}`, tda);
  }

  const a = f.summary.anomalies, an = $("anoms"); an.replaceChildren();
  if (a.threshold == null) {
    node("p", "", "All records were used (anomaly exclusion off).", an);
    node("p", "note", "Switch it on above to leave out operating records the ML model flags. Check its precision first: on the fleet sample it also flags many legitimate records.", an);
  } else {
    node("p", "", `${num(a.excluded)} records of operating vehicles with an ML anomaly score ≥ ${a.threshold} were left out of the sampling pool.`, an);
    if (a.kept_events) node("p", "note", `${num(a.kept_events)} breakdown / absent-driver records were also flagged but kept: they are real events the simulation must include.`, an);
    if (a.record_ids.length) node("p", "note", a.record_ids.slice(0, 30).join(" · ") + (a.excluded > 30 ? " …" : ""), an);
  }

  const cv = f.summary.convergence;
  Plotly.react("c-conv", [
    { x: cv.n.concat([...cv.n].reverse()), y: cv.hi.concat([...cv.lo].reverse()), fill: "toself", type: "scatter",
      line: { width: 0 }, fillcolor: rgba(warm, 0.2), hoverinfo: "skip" },
    { x: cv.n, y: cv.p, type: "scatter", line: { color: warm, width: 2 }, hovertemplate: "%{x:,} scenarios: %{y:.1%}<extra></extra>" }],
    baseLayout("scenarios (log scale)", "P(meet SLA)", { xaxis: { type: "log", gridcolor: cssVar("--line"), title: { text: "scenarios (log scale)" } },
      yaxis: { tickformat: ".0%", gridcolor: cssVar("--line") } }), { displaylogo: false, responsive: true, scrollZoom: true });
  const last = cv.p.length - 1;
  $("conv-note").textContent = last >= 0
    ? `After ${num(f.n_completed)} scenarios: P(meet SLA) = ${pct(cv.p[last])}, 95% CI ${pct(cv.lo[last])} – ${pct(cv.hi[last])}.${f.stopped_early ? " Stopped early by the time budget." : ""}`
    : "";
}

// ── jobs ───────────────────────────────────────────────────────────────────
async function refreshJobs(selectId) {
  const jobs = (await api("/v1/jobs")).filter((j) => j.tests.some((t) => t === "fleet" || t === "scenario"));
  const sel = $("job-select");
  sel.replaceChildren();
  if (!jobs.length) sel.add(new Option("— no jobs yet —", ""));
  for (const j of jobs) {
    const time = new Date(j.created * 1000).toLocaleTimeString();
    sel.add(new Option(`${time} · ${j.dataset_id} · ${j.status}`, j.job_id));
  }
  if (selectId && jobs.some((j) => j.job_id === selectId)) sel.value = selectId;
  $("empty").hidden = jobs.length > 0;
  return jobs;
}

async function poll(generation) {
  if (generation !== state.generation) return;
  try {
    const st = await api(`/v1/jobs/${state.jobId}`);
    if (generation !== state.generation) return;
    if (ACTIVE.includes(st.status)) {
      const p = (st.progress && (st.progress.fleet || st.progress.scenario)) || { done: 0, total: 0 };
      $("progress").hidden = false;
      $("bar").style.width = p.total ? `${(100 * p.done) / p.total}%` : "0";
      $("msg").textContent = p.total ? `Simulating: ${num(p.done)} / ${num(p.total)} ${state.unit}` : `Job ${st.status}…`;
      $("rerun").disabled = true;
      state.timer = setTimeout(() => poll(generation), POLL_MS);
      return;
    }
    $("progress").hidden = true;
    $("rerun").disabled = false;
    if (st.status === "cancelled") { $("msg").textContent = "This run was cancelled."; return; }
    $("msg").textContent = "";
    const res = await api(`/v1/jobs/${state.jobId}/result`);
    if (res.fleet || res.scenario) {
      $("whatif").hidden = false;
      if (res.fleet) render(res.fleet); else renderScenario(res.scenario);
      renderBacktest((res.fleet || res.scenario).summary.backtest);
      renderRelationships(res.relationships, (res.errors || {}).relationships);
      renderMapper(state.jobId, generation);
    } else {
      showError(`The simulation failed: ${Object.values(res.errors || {}).join("; ") || "no result"}`);
      return;
    }
    setDownloads(true);
    showError("");
    refreshJobs(state.jobId);
  } catch (e) {
    showError(e.message);
  }
}

function selectJob(jobId) {
  clearTimeout(state.timer);
  state.generation += 1;
  state.jobId = jobId || null;
  $("result").hidden = true;
  $("whatif").hidden = true;
  setDownloads(false);
  $("nav-live").href = jobId ? `/?job=${encodeURIComponent(jobId)}` : "/";
  const url = new URL(location.href);
  if (jobId) url.searchParams.set("job", jobId); else url.searchParams.delete("job");
  history.replaceState(null, "", url);
  if (jobId) poll(state.generation);
}

async function rerun() {
  if (!state.jobId) return;
  const fleet = {
    fleet_size: Number($("in-fleet").value) || null,
    delivery_target_h: Number($("in-target").value) || null,
    sla_on_time: Number($("in-sla").value) / 100 || null,
    exclude_anomalies_above: $("in-clean").checked ? 0.6 : null,
  };
  for (const k of ["fleet_size", "delivery_target_h", "sla_on_time"]) if (fleet[k] == null) delete fleet[k];
  const scenario = { exclude_anomalies_above: $("in-clean").checked ? 0.6 : null };
  if (Number($("in-period").value)) scenario.period_size = Number($("in-period").value);
  const params = state.kind === "scenario" ? { scenario } : { fleet };
  $("rerun").disabled = true;
  try {
    const job = await api(`/v1/jobs/${state.jobId}/rerun`, { method: "POST", body: JSON.stringify({ n_sims: Number($("in-sims").value) || null, ...params }) });
    await refreshJobs(job.job_id);
    selectJob(job.job_id);
    showError("");
  } catch (e) {
    $("rerun").disabled = false;
    showError(`Re-run failed: ${e.message}`);
  }
}

// ── downloads (the file arrives inside the JSON response as base64) ─────────
function setDownloads(enabled) {
  ["dl-pdf", "dl-xlsx"].forEach((id) => { $(id).disabled = !enabled; });
}

async function download(format, button) {
  if (!state.jobId) return;
  const label = button.textContent;
  button.disabled = true;
  button.textContent = format === "pdf" ? "Building PDF…" : "Building Excel…";
  try {
    const f = await api("/v1/reports/job", { method: "POST", body: JSON.stringify({ job_id: state.jobId, format }) });
    const bytes = Uint8Array.from(atob(f.content), (ch) => ch.charCodeAt(0));
    const url = URL.createObjectURL(new Blob([bytes], { type: f.content_type }));
    const a = document.createElement("a");
    a.href = url;
    a.download = f.filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    showError("");
  } catch (e) {
    showError(`The ${format === "pdf" ? "PDF" : "Excel file"} could not be created: ${e.message}`);
  } finally {
    button.textContent = label;
    button.disabled = false;
  }
}

async function init() {
  $("job-select").addEventListener("change", (e) => selectJob(e.target.value));
  $("rerun").addEventListener("click", rerun);
  $("dl-pdf").addEventListener("click", (e) => download("pdf", e.currentTarget));
  $("dl-xlsx").addEventListener("click", (e) => download("xlsx", e.currentTarget));
  document.querySelectorAll(".seg button[data-tda]").forEach((b) => b.addEventListener("click", () => {
    state.tdaView = b.dataset.tda;
    try { localStorage.setItem("mc-tda-view", state.tdaView); } catch { /* storage unavailable */ }
    drawMapper();
  }));
  try { state.tdaView = localStorage.getItem("mc-tda-view") === "galaxy" ? "galaxy" : "mapper"; } catch { /* storage unavailable */ }
  try {
    await api("/health");
    $("health-dot").className = "dot ok";
  } catch (e) {
    $("health-dot").className = "dot down";
    showError(`Service unreachable: ${e.message}`);
    return;
  }
  try {
    const jobs = await refreshJobs();
    const wanted = new URLSearchParams(location.search).get("job");
    const linked = wanted && jobs.find((j) => j.job_id === wanted);
    if (wanted && !linked) {
      showError(`Job ${wanted} is not available (it expired, or it was started before the service kept jobs across restarts). `
        + "Press Monte Carlo ↗ in CortXplorer to run the simulation again; when it is done, Generate report opens it here.");
      $("empty").hidden = true;
    }
    const first = linked || jobs[0];
    if (first) { $("job-select").value = first.job_id; selectJob(first.job_id); }
  } catch (e) {
    showError(`Could not load jobs: ${e.message}`);
  }
}

init();
